cat <<EOF > .gitlab-ci.yml
stages:
  - build
  - test
  - push
  - deploy

variables:
  DOCKER_IMAGE: "your-dockerhub-username/my-devops-app"

before_script:
  - echo "Starting GitLab CI/CD pipeline..."

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .

test:
  stage: test
  script:
    - echo "Running tests..."
    - docker run --rm $DOCKER_IMAGE node index.js | grep "Hello from Dockerized CI/CD!"

push:
  stage: push
  script:
    - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
    - docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $DOCKER_IMAGE:$CI_COMMIT_REF_NAME

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - ssh user@your-server "docker pull $DOCKER_IMAGE:$CI_COMMIT_REF_NAME && docker run -d $DOCKER_IMAGE:$CI_COMMIT_REF_NAME"
